[package]
name = "test-harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linkme = '0.3'
rayon = '1'
walkdir = '2'
owo-colors = '3'
backtrace = '0.3'
bstr = '1'
